### PR TITLE
Long overdue, Jugglenaut

### PR DESCRIPTION
**Pull request by IdkSomethingTemporary**
Stuff:
    1. I have the memory of a goldfish. Case and point: I forgot my password
    2. Anyways juggle, long overdue and 1 scrapped idea later
  
**Jugglenaut:**
     - Weapon is a mix between newton and placeholder, but still stays true to the gravity/impulse theme, with some extra chip damage so it's not entirely unarmed
     - Jump retooled into a demi-Dgun with a massive amount of damage and impulse
     - Fills the frontline tank niche with a massive HP pool (almost 60k) and regen (almost 1k)

"The Jugglenaut is... well, 2 gravity manipulation devices stuck on 15.79 kilotons of nothing but solid armor. The ultimate frontline bulwark. It can disrupt enemy formations with gravity fields strong enough to rend units apart while soaking in enemy fire with it's utterly impervious armor. Though it's autorepair systems are of an antiquated design, the sheer size of them allows it to shrug off most weapons fire. And when push comes to shove, overloading of the hydraulics systems allows it to perform a jump... and crash down with the force of a tactical nuke, leveling hills and sending anything that survived the shockwave flying."

### CODE REVIEW

**Comment by IdkSomethingTemporary** [comment]
Balance is a bit dubious...
I haven't tested it against real players yet, and the AI is notoriously bad at dealing with heavies (back in the days you could just walk your comm into brutal's base and win, nowadays it's better but still not up to what it takes to kill FW striders), but it seems to be a bit overpowered VS the AI (well, given the fact that I floated 60k, spawned 5 ancient fabs for the AI and my team was *still* winning, I think the AI is just skill issue)

**Comment by Arch-Shaman** [comment]
4050 is a bit on the low side of the cost spectrum, but that's minor and something that can be pushed around as it hits stable. Better to start a bit on the overtuned side than undertuned. I'm a bit concerned about 950 regen though. This might be a bit high. Past that, the only real action item it needs is a rename :P

**Comment by IdkSomethingTemporary** [comment]
I'll look into fiddling with the stats, Juggle in Vanilla is one the lower side of the cost spectrum so I though it'll fit for it to be one of the lower cost FW striders. The Regen probably is a bit too high, and I'll probably also tone down the damage to make it fit it's price and role more. I'll think of a name tommorow, since 1:20am isn't a great time to think of names...

How do these tweaks sound to you?
regen:  950 -> 750
DPS:  2x250 -> 2x167
Cost:  4050 -> 4350

**Comment by Arch-Shaman** [comment]
Maybe around 200-350 regen? For comparison colossus is 600 at its highest
but lacks the massive health pool here (as by the time it gets that low it
will be near death and can get spiked)

su 30. lokak. 2022 klo 10.25 IdkSomethingTemporary ***@***.***>
kirjoitti:

**Comment by IdkSomethingTemporary** [comment]
350 sounds like a good number. I agree with you that it's probably better to have new stuff be a bit overpowered so that people will use them more and allow us to better gauge it's effectiveness when it comes time to nerf it into line. 
Some suggestions for names include "Doomball", "Gravitas", "Bulwark" and "Monolith"
...
oh and "JUGGLENAUT!!!" but that's probably more on the unitlevelups side of the modding spectrum

**Comment by Arch-Shaman** [comment]
Gravitas sounds pretty nice. Though that's up to you.

ti 1. marrask. 2022 klo 18.29 IdkSomethingTemporary <
***@***.***> kirjoitti:

**Comment by IdkSomethingTemporary** [comment]
> Though that's up to you.
***laughs in decision paralysis***

**Comment by Arch-Shaman** [comment]
Do what I do: pick the first option that sounds good. 😂 decision crisis
averted. Now entering consequence crisis.

ke 2. marrask. 2022 klo 9.08 IdkSomethingTemporary ***@***.***>
kirjoitti:

**Pull request merged**
