### PR TITLE
Assassin and Knight Commander

### PR DESCRIPTION
**Pull request by HTMLPhoton**
**Enhancements**
 - Knight commander now has access to all the modules
 - Assassin now has an alpha strike ability
 - Context menu now understands Assassin's alpha strike

### CODE REVIEW

**Comment by HTMLPhoton** [comment]
Don't commit yet, there's a few issues that need to be sorted out

**Comment by HTMLPhoton** [comment]
This is now safe for merging

**Review by Arch-Shaman — COMMENTED** [review]
I'm unsure of enabled = always works.

**Review by Arch-Shaman — APPROVED** [review]
Oh. Its commented. Never mind. I just woke up so.. kinda slow right now.

**Pull request merged**
