### PR TITLE
Let this be a memorial to my stupidity

### PR DESCRIPTION
**Pull request by HTMLPhoton**
I forgot to change CAS in #181

### CODE REVIEW

**Comment by HTMLPhoton** [comment]
Aaaannd i think I screwed something up

**Comment by HTMLPhoton** [comment]
No wait, I think it's just because of the tabs I added (I added a if statement that contained a large amount of the code within it, so I think that's what's giving a false positive)

**Comment by Arch-Shaman** [comment]
Is this ready?

**Comment by Arch-Shaman** [comment]
Monument to stupidity erected.
Bonus to ego flagellation: +50%

**Pull request merged**
