### PR TITLE
[WIP] Kodachi -> Trailblazer

### PR DESCRIPTION
**Pull request by HTMLPhoton**
There are still finalizations that need to be done, such as a proper description, helptext, ~~as well as a CEG for booster.~~ (Done) I am creating this PR now so you can review the numbers ahead of time, as I do have to admit that I have a horrible sense of balance.

Trailblazer:
- Napalm gun replaced with Commando-style napalm sprayer. 240 elmos range, 6 shots per second and 12 damage per shot (total 72 dps). This weapon also acts as a booster when not in use, so firing it reduces the speed of trailblazer down to 40% of base speed. I have decided not to add the sweeping as I feel it would be too much complexity for this 1 unit.
- Speed increased to 4.7, acceleration increased to 0.725, breaking rate increased to 1.45

Dgun: Afterburner Overload (Inspired by the old Dgun that still existed in the code):
- Reload time of 10 seconds, duration of 3 seconds.
- Disables main weapon for entirety of duration. Boosts speed up to 2x for entirety of duration.
- While active, the Trailblazer would leave a trail of (quite deadly) napalm behind it. (80 elmos radius, 120 dps, 16 sec lifetime)
- **This ability costs 150 HP per usage!**

### CODE REVIEW

**Comment by HTMLPhoton** [comment]
Annnnd I misclicked. This is suppose to be a WIP commit but it's not. **This is not ready for merging dispite github saying so! blame me for that**

**Comment by HTMLPhoton** [comment]
I have decided to Tweak some stats around as an experimentation.

Cost: 180 -> 230
DPS: 72 -> 114
Range: 240 -> 270
Afterburner Reload: 10s -> 15s
Afterburner Dps: 120ea -> 160ea
Afterburner HP cost: 150 -> 400
Afterburner Duration: 3s -> 4s

**Comment by Arch-Shaman** [comment]
This sounds really cool actually. The mechanic with damaging self is interesting. How does it interact with currentHP = HPCost - 1?

**Comment by Arch-Shaman** [comment]
Also: don't worry about balance. Look at #322. Even I'm bad at it 😁

**Comment by HTMLPhoton** [comment]
Currently the afterburner will fire either until the ability runs out or the HP drops below 100 (from the afterburner firing). So if you have less than the needed HP then the ability will just stop early.

**Comment by Arch-Shaman** [comment]
Sounds like a good thing. It would be frustrating to have suicide Kodas

**Comment by Arch-Shaman** [comment]
Let's merge it and find out what happens :P can't get any more fucked than it already is, right?

**Pull request merged**
